CREATE DATABASE IF NOT EXISTS Vehicles;

USE Vehicles;

DROP TABLE IF EXISTS cars;

CREATE TABLE cars(
id int(10) NOT NULL AUTO_INCREMENT,
year_made VARCHAR(4) NOT NULL,
make VARCHAR(30) NOT NULL,
model VARCHAR(30) NOT NULL,
trim VARCHAR(30) NOT NULL,
zero_to_sixty DOUBLE(4,2) DEFAULT NULL,
PRIMARY KEY(id)
);